server:
  port: 8086

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

service:
  activemq:
    queueName: first-queue
    topicName: first-topic
    virtualTopicName1: Consumer.1.VirtualTopic.orders
    virtualTopicName2: Consumer.2.VirtualTopic.orders
